### ISSUE TITLE
How are instructors supposed to find the right order of material?

### ISSUE THREAD

**Issue by choldgraf** [Reproducible-Science-Curriculum/sharing-RR-Jupyter#7]
Apologies if this is a naive question, but I was just looking through the repo trying to find the Binder introduction, and couldn't find it anywhere. In a previous iteration we had all the files for this repository in one folder, that way it was easy to follow with the numbering `01_`, `02_`, etc.

Now it appears that `01_` is in a folder called "episodes", while `02_` is in a folder called "slides". Is there any place that would tell a potential instructor where these files are, what their relation is to one another, etc?

**Comment by hlapp** [comment]
At least for my part, I find it very confusing if there is material that is not in or linked from an episode, i.e., in `_episodes`, or in one of its feeder (containing sources for conversion to episodes) directories, `_episodes_rmd` and `_episodes_notebooks`.

This lesson is I think now following this pattern:
* Episode 01 has a source notebook in `_episodes_notebook/`.
* Episode 02 is directly in Markdown in `_episodes/`, and links to the 02 slideshow in `slides/`, specifically the HTML conversion result from the slideshow source in Notebook format.

The conversion is (semi-)automated. By semi I mean that until this is fully automated through CI, someone still has to run the Makefile command:
```sh
$ make lesson-ipynb
```

So concretely to your question, the episodes can still all be followed from what is numbered in the `_episodes/` directory. You can see the 02 episode in there, right?

**Comment by choldgraf** [comment]
I think what's confusing me is that the content of the episode 2 markdown file is much shorter than what is in the notebook:

https://github.com/Reproducible-Science-Curriculum/sharing-RR-Jupyter/blob/gh-pages/_episodes/02-sharing-binder.md

https://github.com/Reproducible-Science-Curriculum/sharing-RR-Jupyter/blob/gh-pages/slides/02-intro_to_binder.ipynb

so maybe they're just out of sync? (which, to that point, I totally agree there should only ever be 1 master copy of an episode, and any derivatives should be created automatically)

**Comment by hlapp** [comment]
No, they are not out sync. They are two parts of the same episode. There's a link to the slideshow in the episode markdown (in line 21), so they are connected.

I.e., episodes don't get generated from slideshows, the slideshow can only ever be a part (even if the overwhelming part) of an episode. That means any slideshow has to be linked from an episode, so as an instructor (_and_ as a self-guided student) you go through the episodes (including following links to slideshows), not hunt around for what slides there might or might not be that are current and meant to be used. Otherwise I think it gets confusing really fast.

Does that make sense? Maybe I'm missing what you're asking about?

**Comment by choldgraf** [comment]
ahhh I see - no you're totally right, I missed the link to the binder slides because it didn't get "linkified" due to the jekyll markdown syntax. Closing this now!
